steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export GOOGLE_APPLICATION_CREDENTIALS=/workspace/terraform-key
        gcloud secrets versions access latest --secret=terraform-key > $GOOGLE_APPLICATION_CREDENTIALS
  - name: 'gcr.io/cloud-builders/terraform'
    args: ['init']
  - name: 'gcr.io/cloud-builders/terraform'
    args: ['apply', '-auto-approve']
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/terraform-key'
      - 'TF_VAR_project_id=swetham'
      - 'TF_VAR_region=us-central1'
      # Add other Terraform environment variables as needed
secrets:
  - versionName: projects/swetham/secrets/terraform-key
    env: 'GOOGLE_APPLICATION_CREDENTIALS'

