
steps:
    - name: 'bash'
      args: ['echo', 'Hello world!']
      serviceAccount: 'projects/arboreal-path-397504/serviceAccounts/uc1-sa-test-2@arboreal-path-397504.iam.gserviceaccount.com'
      options: 
      Logging: CLOUD_LOGGING_ONLY
    - id: 'terraform init'
      name: 'hashicorp/terraform:1.0.0'
      script: terraform init
    - id: 'terraform plan'
      name: 'hashicorp/terraform:1.0.0'
      script: terraform plan