steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export NON_DEFAULT_SA_KEY=/workspace/non-default-sa-key.json
        gcloud secrets versions access latest --secret=terraform-key > $NON_DEFAULT_SA_KEY
  - name: 'gcr.io/cloud-builders/terraform'
    args: ['init']
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/non-default-sa-key.json'
      - 'TF_VAR_project_id=swetham'
      - 'TF_VAR_region=us-central1'
      # Add other Terraform environment variables as needed
  - name: 'gcr.io/cloud-builders/terraform'
    args: ['apply', '-auto-approve']
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/non-default-sa-key.json'
      - 'TF_VAR_project_id=swetham'
      - 'TF_VAR_region=us-central1'
      # Add other Terraform environment variables as needed

