steps:
# Step to create a service account using a module
- name: 'hashicorp/terraform:latest'
  - 'init'
  dir: './IAM'

- name: 'hashicorp/terraform:latest'
   - 'plan'
  dir: './IAM' 

- name: 'hashicorp/terraform:latest'
  args:
   - 'apply'
   - '-auto-approve'
  env:
    - 'TF_VAR_project_id=${PROJECT_ID}'
    - 'TF_VAR_service_account_name=my-service-account'
  dir: './IAM'

# Step to create a bucket for terraform backend

- name: 'hashicorp/terraform:latest'
  args:
   - 'apply'
   - '-auto-approve'
   env:
      - 'TF_VAR_project_id=${PROJECT_ID}'
      - 'TF_VAR_service_account_email=$(cat ./IAM/service_account_email.txt)'
      - 'TF_VAR_bucket_name=my-terraform-bucket'
   dir: './GCS'




  

  