options:
    serviceAccount: 'sa-for-uc-test-1@swetham.iam.gserviceaccount.com'
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file= ./key.json
  - name: 'hashicorp/terraform'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        terraform init
        terraform plan
        terraform apply -auto-approve
