---
steps:
  - name: bash
    args:
      - echo
      - Hello world!
logsBucket: gs://sceg-buck-for-sf-327
serviceAccount: projects/arboreal-path-397504/serviceAccounts/uc1-sa-test-2@arboreal-path-397504.iam.gserviceaccount.com
options:
  logging: GCS_ONLY

---
steps:
  - id: terraform init
    name: hashicorp/terraform:1.0.0
    script: terraform init
  - id: terraform plan
    name: hashicorp/terraform:1.0.0
    script: terraform plan
  